name = "CloudAtlas"
uuid = "b31a9ccd-01a9-4409-bcc3-9c4abd24a9a3"
version = "0.1.0"
authors = ["John F. Gibson <johnfgibson@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StringBuilders = "db12335b-fddc-5e1b-b0ee-42071d21ae50"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"


[extensions]
# Extension name = triggering package(s)
CloudAtlasVisualizationExt = "CairoMakie"
[compat]
LinearAlgebra = "1.12.0"
OffsetArrays = "1.17.0"
Polynomials = "4.1.0"
SparseArrays = "1.12.0"
StaticArrays = "1.9.15"
StringBuilders = "0.3.3"
